Issue#SB-23758 DF>>Portal>>Design QA observations
Sunbird-Ed/discussions-UI pull request #117
Opened 2021-04-07 16:12 UTC by ArtiSingh23

2021-04-08 05:58 UTC, vinukumar-vs requested changes

2021-04-08 05:58 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/discussion-details/discussion-details.component.html
> +                 <img src="./assets/discussion-ui/images/views.svg" alt="profit-image" width="16px" height="16px">
Why so many inline styles here for 
width & height of the image. 

The same code is duplicated for all the images. define the class & use the same class

2021-04-08 05:58 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/discussion-details/discussion-details.component.html
> +          <div class="discussion-content mb-0" role="link" tabindex="0">
Remove the below commented code

2021-04-08 05:58 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/discussion-details/discussion-details.component.html
> +                            'ws-mat-accent-border':currentFilter !== 'timestamp'}"
Remove the below commented HTML code

2021-04-08 05:58 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/elements/category-card/category-card.component.html
> +      <!-- <span class="dot">{{category.user.username}}</span> -->
Remove the commented HTML Code

2021-04-09 09:39 UTC, VenkatKadiveti approved these changes

2021-04-09 09:39 UTC, VenkatKadiveti commented on projects/discussion-ui/assets/styles/theme.scss
Remove commented code

2021-04-09 09:39 UTC, VenkatKadiveti commented on projects/discussion-ui/src/lib/components/discuss-start/discuss-start.component.scss
>  			}
Maintain proper indentation both HTML, TS and SCSS

2021-04-14 10:01 UTC, merged