Release 3.8.0 fix for the special characters in the create post
Sunbird-Ed/discussions-UI pull request #125
Opened 2021-04-20 09:30 UTC by christyfernandes

2021-04-20 11:04 UTC, sudip-mukherjee requested changes

2021-04-20 11:04 UTC, sudip-mukherjee commented on projects/discussion-ui/src/lib/components/discuss-start/discuss-start.component.ts
Add functional comment for this method: htmlDecode(str)

2021-04-21 05:11 UTC, vinukumar-vs requested changes

2021-04-21 05:11 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/discuss-start/discuss-start.component.ts
> +  /** The htmlDecode() method parses a string containing either HTML or XML */
JSDOC format is not correct.

Is this method only for this component. Can't this method can be used by other components? 
If other components can use, then it should be in util service.

2021-04-21 05:11 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/discuss-start/discuss-start.component.ts
> +  /** The htmlDecode() method parses a string containing either HTML or XML */
This follows the
 SRP principle -> This is not related to this component.
 DRY principle -> If other components requires the same method they have to copy-paste the same in another component
 
 @christyfernandes @sudip-mukherjee 

This mehtod is

2021-04-21 06:19 UTC, vinukumar-vs approved these changes

2021-04-21 06:19 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/services/discuss-utils.service.ts
> +   * @param  {any} str
Start adding the description for the parameters as well
Add example also. It helps to understand the code better.

2021-04-21 06:19 UTC, merged