Issue #SB-24311 fix: The created topics are not displayed - only 5 topics are displayed by default
Sunbird-Ed/discussions-UI pull request #138
Opened 2021-04-27 07:34 UTC by kamaleeswary

2021-04-27 12:24 UTC, balakrishna10 approved these changes

2021-04-27 12:42 UTC, vinukumar-vs requested changes

2021-04-28 04:18 UTC, vinukumar-vs approved these changes

2021-04-28 04:18 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/discuss-home/discuss-home.component.ts
> +    if (this.elementView && this.elementView.nativeElement) {
Good to have a line comment here what are we doing here & why did we used "ngAfterViewChecked" method

2021-04-28 04:18 UTC, merged