Issue #SB-26889 fix: bug: Entering 10 times Space button Post Reply button is enabling
Sunbird-Ed/discussions-UI pull request #205
Opened 2021-11-22 09:44 UTC by kamaleeswary

2021-11-22 10:30 UTC, vinukumar-vs approved these changes

2021-11-22 10:30 UTC, vinukumar-vs approved these changes

2021-11-22 10:39 UTC, vinukumar-vs requested changes

2021-11-22 10:39 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/discuss-start/discuss-start.component.ts
> +      if (valueNoWhiteSpace.trim() === '' || valueNoWhiteSpace !== valueNoWhiteSpace.trim()) {
Why are we allowing user to type empty space for the first charecter. Disable/ignore is user is giving space at the first charecter itself.

2021-11-23 10:06 UTC, VenkatKadiveti approved these changes

2021-11-23 10:13 UTC, vinukumar-vs approved these changes

2021-11-23 10:14 UTC, merged