Task#SB-22655 feat: configure driven menu options
Sunbird-Ed/discussions-UI pull request #82
Opened 2021-02-17 05:53 UTC by arunpilli21

2021-02-18 05:59 UTC, vinukumar-vs requested changes

2021-02-18 05:59 UTC, vinukumar-vs commented on projects/discussion-ui/src/lib/components/my-discussion/my-discussion.component.ts
> +    if ( this.discussService.userName) {
Is localstorage is removed in another components as well
Categories, Tags?

2021-02-18 05:59 UTC, vinukumar-vs commented on projects/discussion-ui/src/public-api.ts
> +export *  from './lib/models/discussion-config.model';
This model is not added/exist

2021-02-18 07:05 UTC, arunpilli21 commented on projects/discussion-ui/src/public-api.ts
> +export *  from './lib/models/discussion-config.model';
Added the model

2021-02-19 10:53 UTC, vinukumar-vs approved these changes

2021-02-19 10:54 UTC, merged